spring.main.banner-mode=OFF
spring.output.ansi.enabled=NEVER
logging.pattern.console=%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m [%X{traceId}:%X{spanId}]%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
