spring.application.name=playwright
server.servlet.context-path=/playwright
server.port=8080

# framework-starter
management.endpoint.health.probes.enabled=true

# jaeger
opentracing.jaeger.service-name=FC:playwright-http-playwright/index
opentracing.jaeger.enabled=true
opentracing.jaeger.const-sampler.decision=true
opentracing.jaeger.probabilistic-sampler.sampling-rate=1
opentracing.jaeger.enable128-bit-traces=false
opentracing.jaeger.log-spans=false
opentracing.jaeger.remote-controlled-sampler.sampling-rate=0

# playwright
playwright.executable.path=${PLAYWRIGHT_EXECUTABLE_PATH}
